//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimiento
    {
        public int Id { get; set; }
        public string NombreRequerimiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioResponsable { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaSolucion { get; set; }
        public Nullable<int> Severidad { get; set; }
        public Nullable<int> Categoria { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Severidad Severidad1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
